### ISSUE TITLE
Install `wp-pay*` packacges in `packages`?

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay-with-mollie-for-contact-form-7#3]
https://github.com/pronamic/wp-pronamic-pay-with-mollie-for-contact-form-7/blob/9aed35522cdc6d4a85884f0e6b4fe55c76ba8c40/composer.json#L30-L32

Reverse of:

- https://github.com/pronamic/wp-pronamic-pay-with-mollie-for-contact-form-7/issues/2

That way these strings will be picked up by https://translate.wordpress.org/projects/wp-plugins/pronamic-pay-with-mollie-for-contact-form-7/stable/nl/default/.

**Comment by remcotolsma** [comment]
I'm not sure this is possible: https://getcomposer.org/doc/faqs/how-do-i-install-a-package-to-a-custom-path-for-my-framework.md → https://github.com/composer/installers#current-supported-package-types.

> ## Should we allow dynamic package types or paths? No
> 
> What are they? The ability for a package author to determine where a package
> will be installed either through setting the path directly in their
> `composer.json` or through a dynamic package type: `"type":
> "framework-install-here"`.
> 
> It has been proposed many times. Even implemented once early on and then
> removed. Installers won't do this because it would allow a single package
> author to wipe out entire folders without the user's consent. That user would
> then come here to yell at us.
> 
> Anyone still wanting this capability should consider requiring <https://github.com/oomphinc/composer-installers-extender>.

We could (ab)use the `wordpress-plugin` type?

**Comment by rvdsteege** [comment]
Unfortunately, wildcards like in `wp-pay*` didn't work 😢 Now using the `vendor:` prefix.

- https://github.com/composer/installers#custom-install-paths
- https://github.com/composer/installers/blob/main/src/Composer/Installers/BaseInstaller.php#L110-L126
