### ISSUE TITLE
Add GitHub social preview 1280×640px

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay-with-mollie-for-contact-form-7#6]
For https://github.com/pronamic/wp-pronamic-pay we have the following image:
https://repository-images.githubusercontent.com/5261169/5758c496-b269-418b-8b7a-1c3ae29af98c

We need one for this plugin as wel in the `1280×640px` format:
https://github.com/pronamic/wp-pronamic-pay-with-mollie-for-contact-form-7/settings

> Upload an image to customize your repository’s social media preview.
>
> Images should be at least 640×320px (1280×640px for best display).

**Comment by kjtolsma** [comment]
![github-mollie-contact-form-7](https://user-images.githubusercontent.com/1701552/222726511-e038bcce-02ab-4413-8ad7-25116753716f.png)
