### ISSUE TITLE
Update url on Installation tab at wordpress.org

### ISSUE THREAD

**Issue by LeoOosterloo** [pronamic/wp-pronamic-pay-with-mollie-for-contact-form-7#7]
The same as for the Gravity Forms plugin:

On the installation tab there is a link to the following url:
https://www.pronamicpay.com/en/manuals/how-do-you-link-pronamic-pay-to-contact-form-7/

The correct url is:
https://www.pronamicpay.com/en/manuals/how-to-connect-pronamic-pay-to-contact-form-7/

**Comment by LeoOosterloo** [comment]
Also the title of the manual is not a question, it's an instruction.

> How to connect Pronamic Pay to Contact Form 7

**Comment by remcotolsma** [comment]
> On the installation tab there is a link to the following url:
> https://www.pronamicpay.com/en/manuals/how-do-you-link-pronamic-pay-to-contact-form-7/
> 
> The correct url is:
> https://www.pronamicpay.com/en/manuals/how-to-connect-pronamic-pay-to-contact-form-7/

Changed in https://github.com/pronamic/wp-pronamic-pay-with-mollie-for-contact-form-7/commit/89b4d6efc13eb5a0e380c9f00b2689e4a420e3d5:

https://github.com/pronamic/wp-pronamic-pay-with-mollie-for-contact-form-7/blob/89b4d6efc13eb5a0e380c9f00b2689e4a420e3d5/readme.txt#L44

> Also the title of the manual is not a question, it's an instruction.
> 
> > How to connect Pronamic Pay to Contact Form 7

Unless there's a question mark behind it 😉, then it's a question. Do you want to remove a question mark somewhere, or what do you want to achieve with this comment?

**Comment by LeoOosterloo** [comment]
> Unless there's a question mark behind it 😉, then it's a question. Do you want to remove a question mark somewhere, or what do you want to achieve with this comment?

The question mark should be removed from the link on wordpress.org. So it is the same as the title of the instruction manual.

The same should be done for the link on the page of Pronamic Pay for Gravity Forms: https://github.com/pronamic/wp-pronamic-pay-with-mollie-for-gravity-forms/issues/2

**Comment by remcotolsma** [comment]
Using a question mark is not necessarily wrong? Removed in https://github.com/pronamic/wp-pronamic-pay-with-mollie-for-contact-form-7/commit/ee428c46bd4be7d485d66635139d0128e3007145.
